// saboresActionTypes.ts
export const FETCH_SABORES_PENDING = "FETCH_SABORES_PENDING";
export const FETCH_SABORES_SUCCESS = "FETCH_SABORES_SUCCESS";
export const FETCH_SABORES_FAILURE = "FETCH_SABORES_FAILURE";
